alias: postprocess-question-classification
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
default_variation: full
deps:
- tags: set,echo-off,win
- tags: get,sys-utils-cm
env:
  CM_DATASET: QUESTION-TOPIC
new_env_keys: []
tags:
- postprocess
- question-classification
- go
- qa
- question-topic
uid: 6cecd6d2d34246e0
variations:
  cse-1:
    env:
      CM_DATASET_DEPARTMENT: cse
      CM_DATASET_SIZE: '1'
  cse-500:
    env:
      CM_DATASET_DEPARTMENT: cse
      CM_DATASET_SIZE: '500'
  cse-full:
    env:
      CM_DATASET_DEPARTMENT: cse
      CM_DATASET_SIZE: '1000'
      CM_IMAGENET_FULL: 'yes'
  full:
    env:
      CM_DATASET_SIZE: '1000'
      CM_DATASET_VER: '2022'
      CM_IMAGENET_FULL: 'yes'
