alias: get-ml-model-question-classification
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
default_variation: rh
deps:
- tags: set,echo-off,win
- names:
  - original-dataset
  tags: get,dataset,original,question-topic,go
- tags: get,preprocessed,dataset,go,qa,question-topic
env:
  MLC_DATASET: QUESTION-TOPIC
new_env_keys:
- MLC_DATASET_SELECTED_MODEL_*
- MLC_ML_MODEL
- MLC_DATASET_TRAINED_MODEL_TFIDQ
tags:
- get
- ml-model
- question-classification
- go
- qa
- question-topic
uid: 5562e8fa529f49bd
variations:
  rh:
    deps:
    - tags: go,qa,question-topic,train-model,ml-model-rh
    env:
      MLC_ML_MODEL_NAME: go_1
  rt:
    deps:
    - tags: go,qa,question-topic,train-model,ml-model-rt
    env:
      MLC_ML_MODEL_NAME: go_2
