alias: train-ml-model-question-classification-rt
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
default_variation: full
deps:
- tags: set,echo-off,win
- names:
  - python
  - python3
  tags: get,python3
- tags: get,dataset,original,question-topic,go
- tags: get,preprocessed,dataset,go,qa,question-topic
- tags: get,generic-python-lib,_pandas
- tags: get,generic-python-lib,_numpy
- tags: get,generic-python-lib,_setfit
- tags: get,generic-python-lib,_matplotlib
env:
  MLC_DATASET: QUESTION-TOPIC
new_env_keys:
- MLC_DATASET_TRAINED_MODEL*
- MLC_ML_MODEL*
tags:
- go
- qa
- question-topic
- train-model
- ml-model-rt
uid: aa3003a15aea411d
variations:
  cse-1:
    env:
      MLC_DATASET_DEPARTMENT: cse
      MLC_DATASET_SIZE: '1'
  cse-500:
    env:
      MLC_DATASET_DEPARTMENT: cse
      MLC_DATASET_SIZE: '500'
  cse-full:
    env:
      MLC_DATASET_DEPARTMENT: cse
      MLC_DATASET_SIZE: '1000'
      MLC_IMAGENET_FULL: 'yes'
  full:
    env:
      MLC_DATASET_SIZE: '1000'
      MLC_DATASET_VER: '2022'
      MLC_IMAGENET_FULL: 'yes'
