alias: get-gate-questions
automation_alias: script
automation_uid: 5b4e0237da074764
category: GATE

deps:
  - tags: download,file
    extra_cache_tags: gate-questions
    env:
      MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_GATE_QUESTIONS_JSON_FILE_PATH
    skip_if_env:
      MLC_GATE_QUESTIONS_JSON_FILE_PATH:
      - on
    force_cache: yes

new_env_keys:
 - MLC_GATE_QUESTIONS_JSON_FILE_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- gate-questions
tests:
  run_inputs: []
input_mapping:
  questions_json_path: MLC_GATE_QUESTIONS_JSON_FILE_PATH

uid: 4247623d429e465a
variations:
  gatecse-2025:
    env:
      MLC_DOWNLOAD_URL: https://github.com/GATEOverflow/go-scripts/releases/download/gate2025-contest/questions.json
