alias: gemini-gate-eval
automation_alias: script
automation_uid: 5b4e0237da074764
category: GATE Evaluation
deps: [
  {"name": "parse-gate-question", "tags": "parse-gate-question"},
  {"name": google.generativeai }
]
new_env_keys:
  - GEMINI_API_KEY
  - MLC_GATE_QUESTIONS_JSON_FILE_PATH
  - MLC_GEMINI_MODEL
new_state_keys:
  - output
  - user_prompt
  - system_prompt
tags:
  - gemini-evaluation
  - app
  - question
  - answer
tests:
  run_inputs: []
input_mapping:
  api_key: GEMINI_API_KEY
  model: MLC_GEMINI_MODEL
uid: 7fe2944512654e80
variations:
  gate:
    group: question-source
    default_variations:
      question-subject: cse
      year: year.2025
    env:
      GATE_PAPER_SOURCE: gate
  cse:
    group: question-subject
    env:
      GATE_SUBJECT: cse
  year.2025:
    group: year
    env:
      GATE_YEAR: 2025
  gate,cse,year.2025:
    deps:
      - tags: answering,app,question,gemini,gate