alias: get-preprocessed-dataset-question-topic-go/
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
default_variation: full
deps:
- tags: set,echo-off,win
- tags: get,python3
- tags: get,dataset,original,question-topic,go
- tags: get,generic-python-lib,_tqdm
- tags: get,generic-python-lib,_pandas
env:
  MLC_PREPROCESSED_DATASET: QUESTION-TOPIC
new_env_keys:
- MLC_PREPROCESSED_DATASET_*
tags:
- get
- preprocessed
- dataset
- go
- qa
- question-topic
uid: b934597a9b3b4e51
variations:
  cse-1:
    env:
      MLC_DATASET_DEPARTMENT: cse
      MLC_DATASET_SIZE: '1'
  cse-500:
    env:
      MLC_DATASET_DEPARTMENT: cse
      MLC_DATASET_SIZE: '500'
  cse-full:
    env:
      MLC_DATASET_DEPARTMENT: cse
      MLC_DATASET_SIZE: '1000'
      MLC_IMAGENET_FULL: 'yes'
  full:
    env:
      MLC_DATASET_SIZE: '1000'
      MLC_DATASET_VER: '2022'
      MLC_IMAGENET_FULL: 'yes'
