alias: app-question-classification
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
default_variation: rh
deps:
- tags: set,echo-off,win
- names:
  - python
  - python3
  tags: get,python3
- tags: get,dataset,original,question-topic,go
- tags: get,preprocessed,dataset,go,qa,question-topic
- tags: get,generic-python-lib,_datasets
- tags: get,generic-python-lib,_pandas
- tags: get,generic-python-lib,_numpy
- tags: get,generic-python-lib,_tqdm
- names:
  - scikit-learn
  tags: get,generic-python-lib,_scikit-learn
env:
  MLC_DATASET: QUESTION-TOPIC
new_env_keys:
- MLC_DATASET_OUTPUT_MODEL*
- MLC_ML_MODEL_ANSWER
post_deps:
- tags: postprocess,question-classification
tags:
- app
- question-classification
- topic-classification
- go
- question-topic
uid: f559634052574b50
variations:
  ANTHROPIC_API_KEY.#:
    env:
      ANTHROPIC_API_KEY: '#'
  CLAUDE:
    deps:
    - tags: get,tags,preprocessed,dataset
    - tags: get,generic-python-lib,_package.anthropic
    env:
      MLC_ML_MODEL_PLATFORM: CLAUDE
  CLAUDE_MODEL.#:
    env:
      MLC_ML_MODEL_NAME: '#'
  OPENAI:
    deps:
    - tags: get,tags,preprocessed,dataset
    - tags: get,generic-python-lib,_package.openai
    env:
      MLC_ML_MODEL_PLATFORM: OPENAI
  OPENAI_API_KEY.#:
    env:
      OPENAI_API_KEY: '#'
  OPENAI_MODEL.#:
    env:
      MLC_ML_MODEL_NAME: '#'
  path.#:
    deps:
    - tags: get, ml-model, question-classification, go, qa, question-topic, _rh
    env:
      MLC_DATASET_PATH: '#'
  rh:
    deps:
    - tags: get, ml-model, question-classification, go, qa, question-topic, _rh
    - tags: get,generic-python-lib,_torch
    env:
      MLC_ML_MODEL_NAME: go_1
  rt:
    deps:
    - tags: get, ml-model, question-classification, go, qa, question-topic, _rt
    - tags: get,generic-python-lib,_torch
    env:
      MLC_ML_MODEL_NAME: go_2
  setfit_dataset_path.#:
    deps:
    - tags: get, ml-model, question-classification, go, qa, question-topic, _rt
    env:
      MLC_SETFIT_DATASET: '#'
