alias: get-dataset-question-topic-go
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
default_variation: full
deps:
- tags: set,echo-off,win
env:
  CM_DATASET: QUESTION-TOPIC
new_env_keys:
- CM_DATASET_*
tags:
- get
- dataset
- go
- qa
- original
- question-topic
- train
uid: e6d281efd6864fc6
variations:
  cse-1:
    env:
      CM_DATASET_DEPARTMENT: cse
      CM_DATASET_SIZE: '1'
  cse-500:
    env:
      CM_DATASET_DEPARTMENT: cse
      CM_DATASET_SIZE: '500'
  cse-full:
    env:
      CM_DATASET_DEPARTMENT: cse
      CM_DATASET_FULL: 'yes'
      CM_DATASET_SIZE: '1000'
  full:
    env:
      CM_DATASET_FULL: 'yes'
      CM_DATASET_SIZE: '1000'
      CM_DATASET_VER: '2022'
