alias: get-preprocessed-dataset-gate-questions
automation_alias: script
automation_uid: 5b4e0237da074764
category: GATE
cache: True
deps:
  - tags: get,python3
    names:
    - python
    - python3
  - tags: get,dataset,original,gate-questions
    names:
    - original-dataset
    skip_if_env:
      MLC_GATE_QUESTIONS_JSON_FILE_PATH:
      - on
 
input_mapping:
  questions_json_path: MLC_GATE_QUESTIONS_JSON_FILE_PATH
new_env_keys:
- MLC_PREPROCESSED_GATE_QUESTIONS_JSON_FILE_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- preprocessed
- dataset
- gate-questions
tests:
  run_inputs: []
uid: dc151a04701c40e5
variations:
  gatecse-2025:
    adr:
      original-dataset:
        tags: _gatecse-2025
